### ISSUE TITLE
'vim.Folder' object has no attribute 'host'

### ISSUE THREAD

**Issue by d-zalewski** [evoila/collectsphere#14]
I'm getting below error in collectd logs.

Unhandled python exception in init callback: AttributeError: 'vim.Folder' object has no attribute 'host'

Name: pyvmomi
Version: 6.0.0.2016.6

**Comment by oguzy** [comment]
This is because of the https://github.com/evoila/collectsphere/blob/master/collectsphere.py#L363 part. The object is Folder. I added

if hostFolderChild._wsdlName == "Folder":
                continue

Now i don't see the data at graphite.

**Comment by dennis1987** [comment]
Hi there,
sorry for my late response.
I tried to fix the issue in [6481ab6](https://github.com/evoila/collectsphere/commit/6481ab6ec8bccef55659d148505a75d32e49bc98). I think there could be subfolders under the hostFolderChild, so I have to build a list out of a tree. Please tell me if the commit could fixed the issue.

**Comment by innomation** [comment]
@dennis1987: It appears that the convert_folder_tree_to_list function is grabbing all VM clusters within their respective subfolders. However, after a number of tests, we're only seeing metrics fired off to graphite from the VM cluster(s) placed within the root location only (we've moved clusters outside of their sub-folder into root location for testing, and those began to fire off metrics). We're still investigating, but if you have any insight to share, it would be much appreciated.

Update 1:  read_callback function is pulling up a datacenter value in service_instance, but the compute_resource in datacenter.hostFolder.childEntity is only loading up the cluster placed within the root location. @dennis1987 Can you confirm if your script only cares about 'VM' folders opposed to 'host', 'storage', and 'network' folders?

Update 2: running the python interpreter manually, i've connected to vCenter, and can confirm that the compute_resource that we're seeing is defined as a ClusterComputeResource, but the other compute_resources are listed as a Folder:group-h###. 

```python
print datacenter.hostFolder.childEntity
(ManagedObject) [
   'vim.ClusterComputeResource:domain-c001',
   'vim.Folder:group-h001',
   'vim.Folder:group-h002',
   'vim.Folder:group-h003'
]
```

For testing, I've added a compute_resource._wsdlName == "Folder", but still not seeing any metrics from the clusters placed within the subfolders. 

``` python
if compute_resource._wsdlName == \
    "ComputeResource" \
    or compute_resource._wsdlName == \
    "ClusterComputeResource" \
     or compute_resource._wsdlName == \
     "Folder":
```

Our guess is that the metrics fail for 'Folder' due to there being no vim.folder.host or compute attributes. Is there any way we can dig deeper inside the Folder to gather our clusters for compute_resource?

**Comment by innomation** [comment]
An update, read_callback function is pulling up a datacenter value in service_instance, but the compute_resource in datacenter.hostFolder.childEntity is only loading up the cluster placed within the root location. 

@dennis1987 Can you confirm if your script only cares about 'VM' folders opposed to 'host', 'storage', and 'network' folders?
